# Generated by Django 2.2.3 on 2019-07-11 17:42

from django.db import migrations, models
import langreadingtest.models


class Migration(migrations.Migration):

    dependencies = [
        ('langreadingtest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chineseword',
            old_name='pinyins',
            new_name='pinyin',
        ),
        migrations.AlterField(
            model_name='chineseword',
            name='simplified',
            field=models.CharField(max_length=10, validators=[langreadingtest.models.validate_non_empty]),
        ),
    ]
