# Generated by Django 2.2.3 on 2019-07-13 00:00

from django.db import migrations, models
import langreadingtest.models


class Migration(migrations.Migration):

    dependencies = [
        ('langreadingtest', '0003_auto_20190713_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chineseword',
            name='definition',
            field=models.CharField(max_length=100, validators=[langreadingtest.models.validate_non_empty]),
        ),
        migrations.AlterField(
            model_name='chineseword',
            name='pinyin',
            field=models.CharField(max_length=30, validators=[langreadingtest.models.validate_non_empty]),
        ),
    ]
