# Generated by Django 2.2.3 on 2019-07-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langreadingtest', '0005_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
