# Generated by Django 2.2.3 on 2019-07-21 15:56

from django.db import migrations, models
import django.db.models.deletion
import langreadingtest.models


class Migration(migrations.Migration):

    dependencies = [
        ('langreadingtest', '0007_chineseword_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[langreadingtest.models.validate_non_empty])),
            ],
        ),
    ]
