# Generated by Django 2.2.3 on 2019-07-21 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('langreadingtest', '0008_auto_20190721_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='chineseword',
            name='dataset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='langreadingtest.WordDataset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='dataset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='langreadingtest.WordDataset'),
            preserve_default=False,
        ),
    ]
