# Generated by Django 2.2.3 on 2019-07-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('langreadingtest', '0010_auto_20190725_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chineseword',
            old_name='pdf',
            new_name='normalised_freq',
        ),
    ]
